### ISSUE TITLE
Race condition in the async code when sender drops too quickly

### ISSUE THREAD

**Issue by inetic** [zesterer/flume#120]
When using the `async` code and the `Sender` sends and gets dropped at the wrong time, the `Receiver` won't receive the sent value. Here is how the race happens:

1. Let's have a `Sender` `tx` and a `Receiver` `rx`.
2. User calls `rx.recv().await`, the `RecvFut::poll_inner` func goes [here](https://github.com/zesterer/flume/blob/ad3f4504b60d5f69cc8fff256135f53196ed045c/src/async.rs#L402-L419). So far so good.
3. The next time `RecvFut::poll_inner` is called, we get to [line 377](https://github.com/zesterer/flume/blob/ad3f4504b60d5f69cc8fff256135f53196ed045c/src/async.rs#L377) where we check whether the sender sent something already. At this point the sender has not and thus we do _not_ proceed to the `if` block (line 378).
4. But now the sending thread is scheduled, the sender sends a value and `tx` is dropped.
5. The receiving thread wakes up inside `RecvFut::poll_inner`, on [line 379](https://github.com/zesterer/flume/blob/ad3f4504b60d5f69cc8fff256135f53196ed045c/src/async.rs#L379) it determines that the `Sender` has been destroyed and [`Poll::Ready(Err(RecvError::Disconnected))`](https://github.com/zesterer/flume/blob/ad3f4504b60d5f69cc8fff256135f53196ed045c/src/async.rs#L380) is returned without ever returning the value from the previous step.

I have a solution which I tested and seems to be working fine: instead of testing [`if self.receiver.shared.is_disconnected()` on line 379](https://github.com/zesterer/flume/blob/ad3f4504b60d5f69cc8fff256135f53196ed045c/src/async.rs#L379) we can just check whether the returned value from step `#3` is equal to `Err(TryRecvTimeoutError::Disconnected)`. I'll send a PR.

**Comment by ajitid** [comment]
With the PR merged, I suppose we can close this issue now.

**Comment by zesterer** [comment]
Closed by #121
