### ISSUE TITLE
 Do we need to add a timeout for `recv_async`?

### ISSUE THREAD

**Issue by zhuxiujia** [zesterer/flume#139]
Do we need to add a timeout for `recv_async`?

* Currently, I am using(It works very well) `tokio::time::timeout(d, async { receiver
                .recv_async()
                .await })
                    .await`  
* Do we need to add a timeout for `recv_async_timeout(d:Option<Duration>)`?  or just use tokio::time::timeout?

**Comment by zesterer** [comment]
`tokio::time::timeout` is the thing to use. Flume couldn't implement timeouts without being runtime-specific (or doing something nasty like spinning up a whole new thread for managing timeouts), so it's less to the user to implement things like timeouts with whatever runtime you're making use of (thankfully, it's quite easy to do!).
