### ISSUE TITLE
MPMC support

### ISSUE THREAD

**Issue by zesterer** [zesterer/flume#15]
#14 (and the `mpmc` branch) includes experimental support for cloning `Receiver`. However, performance is not great. This issue exists to discuss ways to improve this.

**Comment by zesterer** [comment]
Fixed by #24

**Comment by alidehghan** [comment]
could you please provide an example of MPMC?

**Comment by zesterer** [comment]
Chumsky doesn't allow the same message to be received by multiple receivers. That's a *broadcast* queue, and invited a fundamentally different design, and a different public interface. There are many other crates in the ecosystem for that. MPMC just means "multiple receivers can pull messages out of the queue, racing one-another". This is often used to implement 'work-stealing' schedulers and thread pools.
