### ISSUE TITLE
Selector::poll polls only the first selection

### ISSUE THREAD

**Issue by pcpthm** [zesterer/flume#31]
Just looking at the code, I noticed this line:

https://github.com/zesterer/flume/blob/53d93a05ca8b705b85c9781cc45626b12f91d356/src/select.rs#L128

The `poll` method is supposedly polling all selections in a pseudorandom order but `self.next_poll` is always zero unless `self.selections.len() >= 2^32`.  I'm not sure what the code meant to be.

**Comment by zesterer** [comment]
The selection code will be overhauled in `flavour-refactor` soon. Regardless, I'll patch this issue now.

**Comment by zesterer** [comment]
This has been fixed in `0.7.2`, just released.
