### ISSUE TITLE
Check if all senders are disconnected

### ISSUE THREAD

**Issue by Flying-Toast** [zesterer/flume#32]
The iterators returned by `Receiver::try_iter()` and `Receiver::drain()` do not differentiate between the channel being empty and all senders having been dropped. So when either of those iterators end, there is no way to tell if the channel is permanently closed or if it is only temporarily empty. Would it be possible to add a public function, perhaps `Receiver::finished() -> bool` to read the private `Receiver.finished` field? That way, a receiver can properly react if the sender thread unexpectedly panics.

One more thing, shouldn't the documentation here actually say "Whether all *senders* have disconnected and there are no messages in any buffer"? https://github.com/zesterer/flume/blob/53d93a05ca8b705b85c9781cc45626b12f91d356/src/lib.rs#L671

**Comment by JMS55** [comment]
`Receiver::iter()` has the same problem in regards to documentation, it should say senders.

**Comment by zesterer** [comment]
@Flying-Toast This behaviour, and many others, are addressed on the `flavor-refactor` branch. Provided you don't rely on the `select` or `async` features, the branch is feature-complete (that is: it's usable as a drop-in replacement for `std::sync::mpsc`). I need to find a few days to properly clean up the branch, merge it to master, and release a new version.

**Comment by zesterer** [comment]
I've just gone through the `try_recv` code and everything looks to be in order. It's only possible for the function return a `TryRecvError::Disconnected` when all senders have been dropped.

Regarding the behaviour of `Iterator::drain`, this is explained in the documentation:

```
/// Take all items currently sitting in the channel and produce an iterator over them. Unlike
/// `try_iter`, the iterator will not attempt to fetch any more values from the channel once
/// the function has been called.
```

This described behaviour seems consistent with what you are describing. If you want an unbounded iterator of received elements, I recommend calling `rx.into_iter()`.

**Comment by Flying-Toast** [comment]
@zesterer, thanks for the response! try_recv is indeed fine - the issue is with try_**iter**. For example:
```Rust
fn main() {
    let (mut tx, rx) = flume::unbounded();

    std::thread::spawn(move || {
        let mut n: u8 = 254;
        loop {
            tx.send(n);
            n += 1; // overflow causes panic
            std::thread::sleep_ms(1000);
        }
    });

    loop {
        // this loop assumes that the sending thread
        // is always alive. If the sending thread panics,
        // this loop will carry on happily, simply returning an empty iterator.
        for i in rx.try_iter() {
            println!("{}", i);
        }

        // Receiver::iter() doesn't have this problem. The above code could be
        // replaced with this (with the consequence that it is no longer non-blocking):
        //
        // for i in rx.iter() {
        //     println!("{}", i);
        // }
        // panic!("Sending thread closed!");
    }
}
```
The same is true for drain - if an empty iterator is returned from drain, the receiving code has no way of knowing if there has been a panic in the sending thread, or if there is simply nothing in the channel.

**Comment by zesterer** [comment]
@Flying-Toast I'm not sure I understand... These are the same behavioural semantics as `std::sync::mpsc`. On the `flavour-refactor` branch there is a `is_disconnected()` method on both `Sender` and `Receiver`. Once this branch becomes the new master I'll release a new version with these features.
