### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by LukasKalbertodt** [zesterer/flume#48]
Hi there and thanks for the project!

I noticed that this project unfortunately does not have a changelog nor release notes nor git tags. That makes it fairly inconvenient to update this dependency. Just now, `cargo outdated` told me that I was using `flume 0.8.x` and that `flume 0.9` was released already. And as far as I see it, the best way for me to find out what changed between those versions (in particular, what breaking changes), is to manually look through the commits. That's not optimal.

I know from experience that maintaining a `CHANGELOG.md` or writing release notes is kind of annoying, but it's really worth a ton for users of the library.

**Comment by zesterer** [comment]
Thanks for the issue, I'll make sure to add this for subsequent breaking changes!
