### ISSUE TITLE
Please document guarantees for how SendError and RecvError can arise

### ISSUE THREAD

**Issue by joshtriplett** [zesterer/flume#51]
Is it guaranteed that the only way to get a `SendError` on an unbounded channel is if the receiver was closed, and the only way to get a `RecvError` on an unbounded channel is if the sender was closed? If so, could you please document that on the error types?

**Comment by Restioson** [comment]
Yes, that is correct according to the docs of send and recv respectively. Documenting it on the types themselves is a good idea.

**Comment by joshtriplett** [comment]
#52 looks great. And yes, when I said "if the sender was closed" I was taking it as a given that recv would return all the available messages first. :)

This matches my observations of flume's behavior, and I'm glad to have it documented.
