### ISSUE TITLE
Add close()

### ISSUE THREAD

**Issue by mehdishojaei** [zesterer/flume#57]
Hi, Thanks for your nice work. Sometimes we need to close the channel to prevent adding new items, and there are some cases that we cannot just drop the sender, so we need to explicitly close the channel without dropping it. Is there any plan to add the **close()** method?

**Comment by zesterer** [comment]
This feels intuitively like a feature that should be handled by a separate Rust primitive. For example, `Option::take`, `ptr::drop_in_place`, or `MaybeUninit::read`. Do none of these cases work for you?

**Comment by Restioson** [comment]
`Option::take` would probably be the best for this usecase but I wonder how much boilerplate it creates.

**Comment by mehdishojaei** [comment]
Yes, I can use `Option::take`, and I'm using it right now. As @Restioson mentioned, It forces a bit of boilerplate but also at the same time it's more explicit. Actually, I compared **flume** with **futures** channel that has `close_channel()`. However thanks a lot.

**Comment by zesterer** [comment]
@mehdishojaei I'm not entire against this. I can imagine it being useful when leaking a channel sender/receiver. Perhaps we'll add it for the next release.
