### ISSUE TITLE
Documentation Request: Does dropping all senders prevent draining a channel?

### ISSUE THREAD

**Issue by fintelia** [zesterer/flume#59]
A quick skim of the code looks to me like disconnected errors are only triggered once the channel is drained, but the documentation suggests otherwise:

> pub fn try_recv(&self) -> Result<T, TryRecvError>
> Attempt to fetch an incoming value from the channel associated with this receiver, returning an error if the channel is empty **or** all channel senders have been dropped.

**Comment by Restioson** [comment]
I think this should just read `returning an error if the channel is empty` - this will never wait, ever, so the number of senders doesn't matter

**Comment by zesterer** [comment]
Ah, yes. This is a case of incorrect documentation. I'll fix this for the next release.

**Comment by zesterer** [comment]
I have released `0.9.2` which fixes this documentation issue, along with many others.
