### ISSUE TITLE
Draining Channel

### ISSUE THREAD

**Issue by JackThomson2** [zesterer/flume#6]
Hi, thanks for the great work. 

Looking into using this, just wondering if it was possible to `drain` a bounded channel? In my app some of the consumers could fall behind and just wanted to clear all currently queued items and start fresh.

Many thanks Jack

**Comment by Restioson** [comment]
And get the elements back (like vec.drain)? Or just clear them?

**Comment by JackThomson2** [comment]
Hi I was hoping just to drop them, if possible.

**Comment by zesterer** [comment]
@JackThomson2 I've just added a `Drain` method on `Receiver`. It'll drain all items currently in the queue into an exact-sized iterator.

**Comment by zesterer** [comment]
I've released `flume 0.6.2` which adds this feature.

**Comment by JackThomson2** [comment]
Thank you that's brilliant.
