### ISSUE TITLE
Single-item latest-only notification channel where writer overwrites atomically rather than blocking

### ISSUE THREAD

**Issue by joshtriplett** [zesterer/flume#60]
As discussed with @zesterer on Zulip:

I'd like to have a channel very similar to a one-item bounded channel, except that when the writer goes to send, if the channel already has an item in it, the writer atomically replaces the item rather than blocking. Readers would block as usual if they receive on an empty channel.

If item 1 is in the channel, and a reader receives in parallel with a writer sending item 2, one of two things would happen: either the reader gets item 1 and the channel contains item 2, or the reader gets item 2 and the channel is empty.

I would use this for notification-style channels where only the latest message is useful, such as "the file is now N bytes long".

**Comment by zesterer** [comment]
I've time to take a look at this now.

My first thought is that another concurrency primitive is best suited to this. Flume's internals are quite specifically geared towards the queuing behaviour. I do think that an independent crate that does this would be quite interesting, however.

**Comment by zesterer** [comment]
I've come up with an initial implementation of a sync-only version of this.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f490d981b62614bf6ab06d76f6bfac30

**Comment by joshtriplett** [comment]
(Closing based on follow-up discussions on Zulip. Worked around using an alternate implementation atop flume channels.)
