### ISSUE TITLE
Please document if send_async ever yields for an unbounded channel

### ISSUE THREAD

**Issue by joshtriplett** [zesterer/flume#61]
Reading the code, as far as I can tell `send_async` will never actually yield for an unbounded channel, making it entirely equivalent to `send` in the unbounded case.

If that's true, it'd be helpful to have that in the documentation.

**Comment by zesterer** [comment]
I'm a little unsure about whether I want to make this an API promise. Although I can't really foresee yielding occurring here, I think I'd have to balance this against the value of such a promise (I do something similar with the `Drain` iterator, where the iterator is technically self-owned, but is tied to the lifetime of the receiver to allow for future implementations that do things differently).

Perhaps I'll put a note about the current implementation not yielding.

**Comment by zesterer** [comment]
This has been addressed in https://github.com/zesterer/flume/commit/58c52c37628583a007fad53b4cce3f8791d899ab

**Comment by joshtriplett** [comment]
The advantage of making this an API promise would be that if you have a function that needs to be called from both sync and async contexts, and it needs to send a message, it's OK to make that function sync and call the synchronous `send` function, rather than making that function async (and creating an async context in the sync callers) or providing two versions of that function.

**Comment by zesterer** [comment]
`send` not blocking for unbounded channels was already a promise made by the API. My concern is more with making it a promise of `async_send`'s future too. As I say, I can't forsee an implementation reason for this to not be the case, but regardless: the promise of `send` being non-blocking should hopefully be sufficient for such purposes as you mention.
