### ISSUE TITLE
Checkpoint Charlie?

### ISSUE THREAD

**Issue by mgeier** [zesterer/flume#62]
The docs to `flume::bounded()` (https://docs.rs/flume/0.9.2/flume/fn.bounded.html) say:

https://github.com/zesterer/flume/blob/89ce729c732b5038e81b9e434c4d757731859c6d/src/lib.rs#L897-L900

What are you referring to with `'Checkpoint Charlie'-style location`?

To me, this sounds like more like a `'Glienicker Brücke'-style location`, see https://en.wikipedia.org/wiki/Glienicke_Bridge.

I don't know whether there were handshakes involved (I wasn't there), but it sounds more like Glienicker Brücke than Checkpoint Charlie to me ....

**Comment by zesterer** [comment]
Perhaps more generic terminology is better. Do you have any suggestions? I think, in hindsight, avoiding descriptions that refer to specific knowledge that the user might not have is probably a good idea.

**Comment by mgeier** [comment]
I have nothing against using cultural or historic references that may not be known to all readers, as long as they can be looked up with reasonable effort.

However, I don't know what exactly you are referring to when you mention "Checkpoint Charlie" in context with "handshake and transfer ownership", even though I do know what "Checkpoint Charlie" is (in fact, I'm living quite close to it).

I would know what you mean if you had used "Glienicker Brücke" (or "Bridge of Spies"), where the "transfer of ownership" would be in reference to the famous exchanges of secret agents.

I looked at some Wikipedia articles in search of what you might be meaning:

* https://en.wikipedia.org/wiki/Checkpoint_Charlie#In_popular_culture
* https://en.wikipedia.org/wiki/Frederic_Pryor#Cold_War_incident

Are you referring to to Frederic Pryor?

I was aware of the multiple agent exchanges that happened at Glienicker Brücke, but I didn't know about the return of Frederic Pryor at Checkpoint Charlie.

**Comment by zesterer** [comment]
I believe I was intending to reference Glienicker Brücke, but didn't think too much about it when writing the docs. I'll change the docs to reference it instead.

**Comment by zesterer** [comment]
Fixed by https://github.com/zesterer/flume/commit/d12effb4eaf3aec03694e0ed1da24e84a7a30d91

**Comment by mgeier** [comment]
Thanks! The link of course helps a lot for people who don't know the reference.
