### ISSUE TITLE
Update nanorand to 0.5.1

### ISSUE THREAD

**Issue by akhilles** [zesterer/flume#63]
There's an issue with versions < 0.5.1 not properly generating random numbers: https://github.com/RustSec/advisory-db/pull/525.

Also, please reconsider the switch from `rand` to `nanorand`. There was no benchmarking done to see if `flume` is actually faster with `nanorand`.

**Comment by zesterer** [comment]
@akhilles Thanks for the information. While this isn't a security vulnerability by itself, it could represent a vector for DoS attacks. I'll update the dependency and try to do some proper benchmarking when I have some free time.

**Comment by zesterer** [comment]
I've released version `0.10.0` which, among other things, addresses this issue.
