### ISSUE TITLE
Support broadcast channel

### ISSUE THREAD

**Issue by maxjoehnk** [zesterer/flume#68]
Right now the cloning of receivers does not emit values for each receiver but only for a single one.

Can we add a `broadcast` method which emits the value (with a `Clone` trait bound?) for each receiver which is connected at the time of sending?

**Comment by Restioson** [comment]
I think this is probably out of scope for flume, and another library should be used here

**Comment by zesterer** [comment]
I agree with @Restioson. Although they seem conceptually similar, the implementation of a broadcast queue is *radically* different to a work-stealing queue. It's not something we can just monkey-patch on top of the current implementation and it's probably best served by a dedicated solution.

**Comment by Restioson** [comment]
> although none that support both sync and async on a single channel like Flume does, sadly

I wrote [barrage](https://crates.io/crates/barrage) a while ago which does support sync and async but it's unoptimised and hasn't had a rigorous correctness overview. Anyway, the go-to options are probably Tokio broadcast channel, bus, or similar. They are the most mature options.

**Comment by zesterer** [comment]
I'm going to close this issue for the reasons mentioned above.
