### ISSUE TITLE
Question: Is message order through a channel preserved?

### ISSUE THREAD

**Issue by jrobhoward** [zesterer/flume#72]
If I have two async tasks (Producer1, Consumer1) operate on a bounded channel, is it normal for the consumer to receive messages out-of-order?

- I understand it may be necessary for MPMC (or MPMC that performs well), but wanted to double-check that message order is not guaranteed/preserved by design for any flume channel configurations (e.g. SPSC/MPMC, async/sync, bounded/unbounded).

Thanks-

**Comment by zesterer** [comment]
Messages should be received in-order. Obviously, if there is more than one consumer or produces then ordering may change depending on which thread gets the opportunity to perform insertion into the channel first. However, messages originating from a single 'logical thread of execution' (i.e: a kernel thread or an async task) will always be received in the same order that they were sent, no matter how many senders or receivers they are.

TL;DR: Yes
