### ISSUE TITLE
Spinlock exponential backoff has no cap — can hang all threads that touch the lock

### ISSUE THREAD

**Issue by thomcc** [zesterer/flume#74]
https://github.com/zesterer/flume/blob/489c015949d04eec0155101268493829d8149e82/src/lib.rs#L301-L310

This should have a max backoff. If the thread holding the lock is suspended, especially if it's suspended for a while (e.g. if it's a low priority thread, or gets paused in a debugger, or the system is laggy ...), every other thread will continue exponentially increase their backoff. Then, when the thread holding the lock finally gives up, it doesn't matter, since everybody else has hung.

Fixing this should just be a matter of setting a maximum sleep duration. I'd probably put it at 2ms max but honestly it's arbitrary and a better solution is not to use a spinlock for something like this. 

## The part where I tell you not to use a spinlock

You can skip this and just fix the issue if you aren't interested in switching. I don't have the energy or time to debate it, and I don't use flume so I don't really care. The real issue is libstd's mutex being bad enough to push you to this, which I truly hope we eventually fix (it's gotten better though).

In general: you shouldn't use a spinlock here (yes, it's still a spinlock if you call thread::yield_now). It's probably always a bad idea to use them in generic code (it can be okay for very concrete data cases but mostly is a mistake in userspace)... but *especially* given the size of the critical sections in flume (which include... calls into the memory allocator? 🙀), yeah, it seems likely to cause problems.

Calling yield_now like this does not make things better, and mostly just helps out benchmarks, since in those you're very likely to switch to either the thread that has the lock, or to another thread that will immediately switch away, and you don't have very many thread priorities.

You can easily find people telling you not to do this and why if you search for stuff like "sched_yield spinlock" (Linus, unsurprisingly, has some heated words about it that I won't link due to toxicity), but at the end of the day it's just not really a good thing to do and basically just wastes time hammering the kernels runqueue before going to sleep for probably far too long, and degrading UX. (This is true on basically all OSes)

I get why you don't use a Mutex on unix, although I suspect it *might* have gotten better since you tried, but it's still not great. Ideally, an MCS-style adaptive mutex would be good, as you don't need features like timed wait, but IDK of any off the shelf¹.

Anyway, follow this advice or don't — I don't use flume, but I've seen this kind of thing cause problems before. You should fix the backoff cap either way though.

---

¹ Closest I know of: `parking_lot_core` has one [that it uses internally](https://github.com/Amanieu/parking_lot/blob/master/core/src/word_lock.rs). It's not public (nor would it be reasonable to depend on parking_lot for just it), but you could use it as a model — I think you'd probably want to switch to using `std::thread::park`/`std::thread::unpark` over the `thread_parker` stuff though.

That said, obviously you can't write a mutex without unsafe code, (especially not one that performs well). I personally think that is less important than behaving well on modern OSes, but I guess people can disagree about that, and it's probably not a discussion that has a true correct answer.

Using std::sync::Mutex universally let you continue to refrain from unsafe though.

**Comment by zesterer** [comment]
Ah, I just remembered that I fixed this in 3f8a925983d074ce9cec2a4b26b5371ce365092f.

**Comment by thomcc** [comment]
Someone reminded me of this issue, and I had missed your comment on benchmarks justifying this.

> mutexes perform worse on every benchmark I've been able to come up with on *nix systems.

Relying on benchmark numbers to justify use of spinlocks is a common trap for benchmarking concurrency. Spinlocks (especially ones like you're using here) are really great in benchmarking-style scenarios, but much worse behavior in real-world scenarios.

The reason for this is because in a spinlock like the one you have, where you handle contention by yielding to another thread, in a benchmark case, you have all of your doing the same thing (after all, this is the thing you're benchmarking), and so you're very likely to switch to a thread which is either:

1. Already holds the lock, in which case it's going to make progress and release the lock. This is unlikely to happen on the first try if you have several threads.
2. Waiting for the in a similar spin loop (probably even for the same lock), in which case it's going to yield almost immediately. (Giving the kernel another shot at guessing which thread is the one with the lock, and reduces the cost of it picking wrong substantially).

Unfortunately, this style of threading behavior is not typically true for real applications, while it's true of virtually all benchmarks (as having threads which are performing tasks unrelated to what you're benchmarking is virtually guaranteed to make your benchmarks... noisy, to say the least).

IME in real applications, you usually have a lot of threads doing different things, often with various priorities, and so it's unlikely in real-world code that switching to a random thread will happen to pick one which will lead to progress being made on the lock.

This means the cost of the scheduler "guessing wrong" about which thread to switch to in order to make progress on the lock is far higher, and you spend far more time waiting for a lock than you need to.
