### ISSUE TITLE
Add oneshot channel type

### ISSUE THREAD

**Issue by arzg** [zesterer/flume#79]
Would you be open to adding a separate oneshot channel implementation? I haven’t done any benchmarking, but I assume that this could save some heap allocations as only one value has to be stored. Maybe this idea could be extended to include any constant channel capacity using the stable subset of const generics?

**Comment by zesterer** [comment]
I think that a oneshot channel is somewhat tangential to the aims of Flume. I'm not entirely opposed to it, but the implementation as it exists now is not really designed for oneshot and there already exist many good oneshot implementations on crates.io.

> Maybe this idea could be extended to include any constant channel capacity using the stable subset of const generics?

Sadly, `min_const_generics` does not (yet) allow specialisation of a type's definition, so I don't think this is possible.

**Comment by arzg** [comment]
Would you say it would be a good idea then to rename this issue to focus purely on constant channel capacities? Or do you think it will take too long for the required parts of const generics to be stabilised, so we’d be waiting years?

**Comment by zesterer** [comment]
I don't think that this is desirable, even. It's often the case that the capacity is only known at runtime, and this is not a use-case that const generics can account for. Additionally, the runtime overhead that comes with non-constant capacities is negligible so it's not really a reason to change this.

**Comment by arzg** [comment]
Makes sense, thanks for the great library and quick responses :)
