### ISSUE TITLE
Feature: broadcast

### ISSUE THREAD

**Issue by Antiarchitect** [zesterer/flume#92]
Your crate is almost ideal among that I tried (crossbeam-channel and tokio::sync::mpsc). The tastiest features are recv_async and send_async. It would be very nice to have the broadcast feature (i.e. by cloning the receiver by some other method like `clone_for_broadcast()` or something). Because there are situations (like mine) where broadcasting is necessary and all in one library would be very nice.

**Comment by Restioson** [comment]
Broadcasting is a very different kind of channel, and I think it'd require a different implementation entirely - I'm not sure how much shared code there'd be. I tried my hand at writing one once: https://crates.io/crates/barrage, and the impl turned out markedly different to what we have in flume

**Comment by zesterer** [comment]
This was mentioned in #68 previously. While it would theoretically be a nice feature to support, implementing it falls well outside the scope of Flume for a variety of subtle implementation reasons (mentioned on the previous issue).
