### ISSUE TITLE
Future structs don't have `#[must_use]` attributes

### ISSUE THREAD

**Issue by Aeledfyr** [zesterer/flume#93]
While it isn't strictly necessary, adding `#[must_use]` to the futures returned by async methods helps to prevent simple errors of forgetting to await the returned future.

For example, this code causes no warnings, but never actually sends the message on the channel: 
```rust
let (tx, rx) = flume::bounded(1);
tx.send_async("Hello, world!");
```

**Comment by zesterer** [comment]
This is a good idea! I'm going to try to find time to add this before new year.
