### ISSUE TITLE
Consider adding into_iter()

### ISSUE THREAD

**Issue by lu-zero** [zesterer/flume#96]
The current api has `into_stream`, and would be nice to have the same functionality on the sync side as well.

**Comment by zesterer** [comment]
[This exists!](https://docs.rs/flume/latest/flume/struct.Receiver.html#impl-IntoIterator-1)

**Comment by lu-zero** [comment]
Thank you for pointing me to it :) 

I guess I could send you a patch to point in the `iter()` documentation to `into_iter()`.

**Comment by zesterer** [comment]
I'd definitely be willing to accept such an addition!

**Comment by lu-zero** [comment]
I'm tempted to add a into_try_iter, but maybe you'd rather have it after your full overhaul lands.
