### ISSUE TITLE
Values received out-of-order in a single-threaded async single-producer single-consumer scenario (involving tokio::select).

### ISSUE THREAD

**Issue by rzheka** [zesterer/flume#98]
Single producer, single consumer, using `send_async` and `recv_async`. Everything runs on the "current thread" tokio's runtime. One small twist here is the usage of `tokio::select!`.

Here's a short repro:
```rust
fn main() {
    let rt = tokio::runtime::Builder::new_current_thread().build().unwrap();
    rt.block_on(test());
}

async fn test() {
    let (tx, rx) = flume::bounded(4);
    tokio::select! {
        _ = producer(tx) => {},
        _ = consumer(rx) => {},
    }
}

async fn producer(tx: flume::Sender<usize>) {
    for i in 0..100 {
        tx.send_async(i).await.unwrap();
    }
}

async fn consumer(rx: flume::Receiver<usize>) {
    let mut expected = 0;
    while let Ok(value) = rx.recv_async().await {
        //  !!! This assert usually fires after a few values
        assert_eq!(value, expected);
        expected += 1;
    }
}
```

Same experiment with `tokio::sync::mpsc::channel()` works fine:
```rust
async fn test_tokio_channel() {
    let (tx, rx) = tokio::sync::mpsc::channel(4);
    tokio::select! {
        _ = producer_tokio(tx) => {},
        _ = consumer_tokio(rx) => {},
    }
}

async fn producer_tokio(tx: tokio::sync::mpsc::Sender<usize>) {
    for i in 0..100 {
        tx.send(i).await.unwrap();
    }
}

async fn consumer_tokio(mut rx: tokio::sync::mpsc::Receiver<usize>) {
    let mut expected = 0;
    while let Some(value) = rx.recv().await {
        assert_eq!(value, expected);
        expected += 1;
    }
}
```

**Comment by rzheka** [comment]
After some debugging, I see that the following path in `Shared<T>::send()` is taken occasionally:
https://github.com/zesterer/flume/blob/64657a1020c3723bb1ebb094827981021ed04938/src/lib.rs#L480

Was the intention really to `push_front()` here (as opposed to `push_back()`)?

**Comment by Restioson** [comment]
Worth looking into - note that it uses front again at L468

**Comment by zesterer** [comment]
@rzheka Did you have the time to fork, switch to `push_back`, and confirm whether this continues to happen or not?

**Comment by rzheka** [comment]
With `push_back` this doesn't happen, my test works fine (I didn't prepare any PR yet, just investigated and played with it on local repo).
The question, though, is whether this `push_front` was intentional, or it's just a typo?

**Comment by zesterer** [comment]
> The question, though, is whether this push_front was intentional, or it's just a typo?

I suspect that it was a typo. The async code paths are not so well tested, and I believe one (and perhaps both) of these cases are not hit without async code being enabled, and the tests probably don't check for ordering in the cases where they are.

Is there any chance you could open a PR with this change?
